data/mirrors: update Geekpie Association URL
AOSC-Dev/aosc-portal-kiss.github.io pull request #47
Opened 2022-02-27 13:21 UTC by Nyovelt

We have obtained a subdomain from our university's IT services

2022-02-27 18:41 UTC, eatradish approved these changes

2022-02-27 18:43 UTC, eatradish requested changes
Get 403?
![0E1EC0AD-ABF0-4E4E-B584-B6B2DC45F394](https://user-images.githubusercontent.com/19554922/155895388-73885606-3518-457c-b2c8-8b447246c7da.png)

2022-02-28 12:14 UTC, Nyovelt commented
> Get 403? ![0E1EC0AD-ABF0-4E4E-B584-B6B2DC45F394](https://user-images.githubusercontent.com/19554922/155895388-73885606-3518-457c-b2c8-8b447246c7da.png)

Fixed

2022-02-28 12:14 UTC, Nyovelt commented
> Get 403? ![0E1EC0AD-ABF0-4E4E-B584-B6B2DC45F394](https://user-images.githubusercontent.com/19554922/155895388-73885606-3518-457c-b2c8-8b447246c7da.png)

It can be visited now, we have fixed it.

2022-02-28 12:17 UTC, eatradish approved these changes

2022-02-28 12:17 UTC, merged